### ISSUE TITLE
zstack-cli dump failed, if L3 network doesn't have dns or network service.

### ISSUE THREAD

**Issue by youyk** [zstackorg/zstack-utility#4]
zstack-cli -D /tmp/ec2-demo.xml

2015-04-24 10:44:10,934 DEBUG [apibinding.api] async call[url: http://localhost:8080/zstack/api/, request: {"org.zstack.header.identity.APILogOutMsg": {"session": {"uuid": "d658235252234a82aa89822dfc3c3235"}, "timeout": 15000, "sessionUuid": "d658235252234a82aa89822dfc3c3235"}}]
[Async call]: [LogOutAction] Success
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/var/lib/zstack/virtualenv/zstackcli/lib/python2.6/site-packages/zstackcli/cli.py", line 967, in main
    read_config.dump_zstack(options.zstack_config_dump_file)
  File "/var/lib/zstack/virtualenv/zstackcli/lib/python2.6/site-packages/zstackcli/read_config.py", line 391, in dump_zstack
    get_zone(xml_root, session_uuid)
  File "/var/lib/zstack/virtualenv/zstackcli/lib/python2.6/site-packages/zstackcli/read_config.py", line 342, in get_zone
    _add_l3(l2_xml, l2)
  File "/var/lib/zstack/virtualenv/zstackcli/lib/python2.6/site-packages/zstackcli/read_config.py", line 264, in _add_l3
    for dns in dnss:
TypeError: 'NoneType' object is not iterable

**Comment by youyk** [comment]
fixed by: https://github.com/zstackorg/zstack-utility/commit/b4fff76a16f28a8e14ba86fa958e7af531aa70b9
